apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: personal-site
  template:
    spec:
      nodeSelector:
        node-type: worker-lowmem
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
        - name: web
          image: ghcr.io/spicyhek/personal-site
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: personal-site
  namespace: default
spec:
  selector:
    app: personal-site
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
