---
# Source: prometheus-blackbox-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-prometheus-blackbox-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: prometheus-blackbox-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-prometheus-blackbox-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
data:
  blackbox.yaml: |
    modules:
      dns_brendanmanley_a:
        dns:
          preferred_ip_protocol: ip4
          query_name: brendanmanley.com
          query_type: A
          transport_protocol: udp
          valid_rcodes:
          - NOERROR
        prober: dns
        timeout: 5s
      dns_grafana_a:
        dns:
          preferred_ip_protocol: ip4
          query_name: grafana.brendanmanley.com
          query_type: A
          transport_protocol: udp
          valid_rcodes:
          - NOERROR
        prober: dns
        timeout: 5s
      dns_nids_a:
        dns:
          preferred_ip_protocol: ip4
          query_name: nids.brendanmanley.com
          query_type: A
          transport_protocol: udp
          valid_rcodes:
          - NOERROR
        prober: dns
        timeout: 5s
      dns_status_a:
        dns:
          preferred_ip_protocol: ip4
          query_name: status.brendanmanley.com
          query_type: A
          transport_protocol: udp
          valid_rcodes:
          - NOERROR
        prober: dns
        timeout: 5s
      http_2xx:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s
---
# Source: prometheus-blackbox-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: blackbox-prometheus-blackbox-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: http
      protocol: TCP
      name: http
    
  selector:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox
---
# Source: prometheus-blackbox-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-prometheus-blackbox-exporter
  namespace: monitoring
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: blackbox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        helm.sh/chart: prometheus-blackbox-exporter-11.18.0
        app.kubernetes.io/name: prometheus-blackbox-exporter
        app.kubernetes.io/instance: blackbox
        app.kubernetes.io/version: "v0.28.0"
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/config: def42ad363c6e770cfb38f25ba7b38748257f19635b1808a557839d54b0a2a4f
    spec:
      automountServiceAccountToken: false
      serviceAccountName: blackbox-prometheus-blackbox-exporter
      restartPolicy: Always
      
      containers:
      
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.28.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        args:
        - "--config.file=/config/blackbox.yaml"
        ports:
        - containerPort: 9115
          name: http
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: http
        volumeMounts:
        - mountPath: /config
          name: config
      hostNetwork: false
      volumes:
      - name: config
        configMap:
          name: blackbox-prometheus-blackbox-exporter

