apiVersion: v1
kind: ConfigMap
metadata:
  name: zeek-local-policy
  namespace: default
data:
  local.zeek: |
    @load policy/tuning/json-logs

    redef LogAscii::use_json = T;
    redef LogAscii::json_timestamps = JSON::TS_EPOCH;
    redef Log::default_rotation_interval = 1hr;
    redef Log::default_logdir = "/zeek-logs";
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeek
  namespace: default
spec:
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: homelab-control-plane
      containers:
        - name: zeek
          image: zeek/zeek:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          command: ["/usr/local/zeek/bin/zeek"]
          args: ["-i", "eth0", "local"]
          volumeMounts:
            - name: zeek-local-policy
              mountPath: /usr/local/zeek/share/zeek/site/local.zeek
              subPath: local.zeek
              readOnly: true
            - name: zeek-logs
              mountPath: /zeek-logs
      volumes:
        - name: zeek-local-policy
          configMap:
            name: zeek-local-policy
        - name: zeek-logs
          hostPath:
            path: /var/lib/zeek-logs
            type: DirectoryOrCreate
        - name: zeek-state
          hostPath:
            path: /var/lib/mynids-zeek
            type: DirectoryOrCreate
