apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-brendanmanley
  namespace: monitoring
  labels:
    release: mon
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://brendanmanley.com
        - https://grafana.brendanmanley.com
        - https://status.brendanmanley.com
        - https://nids.brendanmanley.com
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-dns
  namespace: monitoring
  labels:
    release: mon
spec:
  interval: 60s
  module: dns_brendanmanley_a
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        dns_name: brendanmanley.com
      static:
        - 1.1.1.1:53
        - 8.8.8.8:53
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-dns-grafana
  namespace: monitoring
  labels:
    release: mon
spec:
  interval: 60s
  module: dns_grafana_a
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        dns_name: grafana.brendanmanley.com
      static:
        - 1.1.1.1:53
        - 8.8.8.8:53
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-dns-status
  namespace: monitoring
  labels:
    release: mon
spec:
  interval: 60s
  module: dns_status_a
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        dns_name: status.brendanmanley.com
      static:
        - 1.1.1.1:53
        - 8.8.8.8:53
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-dns-nids
  namespace: monitoring
  labels:
    release: mon
spec:
  interval: 60s
  module: dns_nids_a
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        dns_name: nids.brendanmanley.com
      static:
        - 1.1.1.1:53
        - 8.8.8.8:53
